language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: LINUX_DEPLOY="true" $TRAVIS_OS_NAME="linux"
compiler:
  - gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgnutls28-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential pkg-config libcurl3-gnutls-dev libc6-dev libevent-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-pip zlib1g-dev wget bsdmainutils automake libssl-dev libprotobuf-dev protobuf-compiler libdb++-dev ntp ntpdate; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user pyblake2 flake8 zmq pytest; fi

before_script:
    - ./zcutil/fetch-params.sh
script:
    - ./zcutil/build.sh -j$(nproc)
after_script:
    - ./qa/pull-tester/rpc-tests.sh
